import React, { useCallback, useEffect, useState } from "react";
import { ImageUploader } from "../components/ImageUploader";
import { CanvasWorkspace } from "../components/CanvasWorkspace";
import { TransformationControls } from "../components/TransformationControls";
import { DownloadOptions } from "../components/DownloadOptions";
import { MatrixDisplay } from "../components/MatrixDisplay";
import { loadWasmModule } from "../wasm/wasmLoader";
import "../styles/home.css";

export default function Home() {
  const [imageData, setImageData] = React.useState<ImageData | null>(null);
  const [wasmModule, setWasmModule] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(true);
  // We'll still keep the transformMatrix in state, but it will be generated by WASM
  const [transformMatrix, setTransformMatrix] = React.useState<number[][]>([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
  ]);
  const [originalDimensions, setOriginalDimensions] = React.useState({ width: 0, height: 0 });
  const [imageFormat, setImageFormat] = React.useState("");
  const [transformedImageData, setTransformedImageData] = React.useState<ImageData | null>(null);
  const [compressionLevel, setCompressionLevel] = React.useState(100);
  const [outputFormat, setOutputFormat] = React.useState("image/jpeg");

  // Add state for transformation parameters
  const [transformParams, setTransformParams] = useState({
    rotationAngle: 0,
    scaleX: 1,
    scaleY: 1,
    flipHorizontal: false,
    flipVertical: false,
    shearX: 0,
    shearY: 0
  });

  // Load WebAssembly module
  useEffect(() => {
    const loadWasm = async () => {
      try {
        setIsLoading(true);
        const module = await loadWasmModule();
        setWasmModule(module);
        console.log('WebAssembly module loaded in Home component');
      } catch (error) {
        console.error('Failed to load WebAssembly module:', error);
      } finally {
        setIsLoading(false);
      }
    };

    loadWasm();
  }, []);

  const handleImageUpload = useCallback((data: ImageData, format: string) => {
    setImageData(data);
    setOriginalDimensions({ width: data.width, height: data.height });
    setImageFormat(format);
    // Reset transformations when a new image is uploaded
    setTransformMatrix([
      [1, 0, 0],
      [0, 1, 0],
      [0, 0, 1]
    ]);
  }, []);

  const handleTransformationChange = useCallback((newMatrix: number[][], params?: any) => {
    setTransformMatrix(newMatrix);
    if (params) {
      setTransformParams(params);
    }
  }, []);

  const handleTransformedImageUpdate = useCallback((data: ImageData) => {
    setTransformedImageData(data);
  }, []);

  return (
    <div className="home-container">
      <header className="app-header">
        <h1>TinyImg - Image Editor</h1>
        {isLoading && <p className="loading-indicator">Loading WebAssembly module...</p>}
      </header>
      
      <main className="app-content">
        <div className="left-panel">
          {!imageData ? (
            <ImageUploader onImageUpload={handleImageUpload} />
          ) : (
            <div className="image-info">
              <h3>Image Information</h3>
              <p>Dimensions: {originalDimensions.width} x {originalDimensions.height}</p>
              <p>Format: {imageFormat}</p>
              <button 
                className="reset-button"
                onClick={() => setImageData(null)}
              >
                Upload New Image
              </button>
            </div>
          )}
          
          {imageData && wasmModule && (
            <TransformationControls 
              onTransformationChange={handleTransformationChange}
              transformMatrix={transformMatrix}
              wasmModule={wasmModule}
            />
          )}
        </div>
        
        <div className="center-panel">
          {imageData ? (
            <CanvasWorkspace 
              imageData={imageData}
              transformMatrix={transformMatrix}
              onTransformedImageUpdate={handleTransformedImageUpdate}
              wasmModule={wasmModule}
            />
          ) : (
            <div className="empty-workspace">
              <p>Upload an image to get started</p>
            </div>
          )}
        </div>
        
        <div className="right-panel">
          {transformedImageData && (
            <DownloadOptions 
              transformedImageData={transformedImageData}
              compressionLevel={compressionLevel}
              outputFormat={outputFormat}
            />
          )}
          
          {imageData && wasmModule && (
            <MatrixDisplay 
              transformMatrix={transformMatrix} 
              transformParams={transformParams}
            />
          )}
        </div>
      </main>
      
      <footer className="app-footer">
        <p>TinyImg - Image Manipulation with WebAssembly</p>
      </footer>
    </div>
  );
}
